// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('kajsApp').controller('MainCtrl', function($scope) {
    $scope.profile = "YOYO TESTING HAHA YE SEN";
  });

}).call(this);
