// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('kajsApp', ['ngRoute']).config(function($routeProvider, $locationProvider, $httpProvider) {
    $locationProvider.html5Mode(true);
    return $routeProvider.when('/', {
      templateUrl: '/views/partials/main.html',
      controller: 'MainController'
    });
  }).controller('MainController', function($scope, $http) {
    $scope.profile = false;
    $scope.jsCode = null;
    return $scope.parseIt = function() {
      $scope.body = {
        jsCode: $scope.jsCode
      };
      console.log($scope.jsCode);
      console.log(typeof $scope.jsCode);
      return $http.post('/api/controller/parse', $scope.body).success(function(parsed) {
        var declaration, _i, _len, _ref;
        console.log(parsed.ast.body);
        $scope.parsedCode = parsed;
        _ref = $scope.parsedCode.ast.body;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          declaration = _ref[_i];
          if ($scope.needVariable === true) {
            if (declaration.type === "VariableDeclaration") {
              $scope.variableError = null;
              break;
            } else {
              $scope.variableError = "You must declare a variable in your code!";
            }
          } else if ($scope.needIf === true) {
            if (declaration.type === "IfStatement") {
              $scope.ifError = null;
              break;
            } else {
              $scope.ifError = "You must use an if statement in your code!";
            }
          } else if ($scope.needFor === true) {
            if (declaration.type === "ForStatement") {
              $scope.forError = null;
              break;
            } else {
              $scope.forError = "You must use a for loop in your code!";
            }
          } else if ($scope.noVariable === true) {
            if (declaration.type === "VariableDeclaration") {
              $scope.variableError = "You must not declare any variables in your code!";
            } else {
              $scope.variableError = null;
              break;
            }
          } else if ($scope.noIf === true) {
            if (declaration.type === "IfStatement") {
              $scope.ifError = "You must not use an if statement in your code!";
            } else {
              $scope.ifError = null;
              break;
            }
          } else if ($scope.noFor === true) {
            if (declaration.type === "ForStatement") {
              $scope.forError = "You must not use a for loop in your code!";
            } else {
              $scope.forError = null;
              break;
            }
          }
        }
      });
    };
  });

}).call(this);
