// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('kajsApp', ['ngRoute']).config(function($routeProvider, $locationProvider, $httpProvider) {
    $locationProvider.html5Mode(true);
    return $routeProvider.when('/', {
      templateUrl: '/views/partials/main.html',
      controller: 'MainController'
    });
  }).controller('MainController', function($scope, $http) {
    $scope.profile = false;
    $scope.jsCode = null;
    $scope.parseIt = function() {
      $scope.body = {
        jsCode: $scope.jsCode
      };
      console.log($scope.jsCode);
      console.log(typeof $scope.jsCode);
      return $http.post('/api/controller/parse', $scope.body).success(function(parsed) {
        console.log(parsed);
        $scope.parsedCode = parsed;
      });
    };
    return console.log($scope.profile);
  });

}).call(this);
