// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('MainCtrl', []).controller('MainController', function($scope) {
    $scope.profile = false;
    console.log($scope.profile);
  });

}).call(this);
