// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('kajsApp', ['ngRoute', 'MainCtrl']).config(function($routeProvider, $locationProvider, $httpProvider) {
    $locationProvider.html5Mode(true);
    return $routeProvider.when('/', {
      templateUrl: '/partials/main.html',
      controller: 'MainCtrl'
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);
